name: STILL IN MOTION
favicon: null
layout_spectrum: 0.24247
typography_spectrum: 0.22478
title: Still In Motion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f1f1f'
    - '#696969'
    - '#d4d4d4'
    - '#f2f2f2'
  brandStrength: 0.125
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
