name: STILL IN MOTION
favicon: null
layout_spectrum: 0.94301
typography_spectrum: 0.22478
title: Still In Motion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f0'
    - '#0096c7'
    - '#6e96ae'
    - '#25241f'
    - '#bdd7e3'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.38069427688606083
purpose: []
